### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by sinanbozkus** [alperkaratas/dev-flow#1]
I'm getting an error while I am using the website.

<img width="797" alt="Screen Shot 2021-01-11 at 01 44 17" src="https://user-images.githubusercontent.com/10330406/104137530-95f1d180-53ae-11eb-96e7-ab7e44698ecd.png">

**Comment by alperkaratas** [comment]
The problem may be because you did not click the search button twice.

<img width="1333" alt="Ekran Resmi 2021-01-11 01 57 14" src="https://user-images.githubusercontent.com/15261155/104137778-6c39aa00-53b0-11eb-891a-138193b57271.png">

**Comment by alperkaratas** [comment]
Is the problem solved?

**Comment by sinanbozkus** [comment]
Yes, but why do I need to click twice? :D

**Comment by sinanbozkus** [comment]
Yes, but still getting an error when clicking first.
The second is ok.

**Comment by alperkaratas** [comment]
I'm working on that error.
